// Code generated by go generate; DO NOT EDIT.
// This file was generated from GraphQL schema

package module

type Enum__TypeKind string

const Enum__TypeKindSCALAR Enum__TypeKind = "SCALAR"
const Enum__TypeKindOBJECT Enum__TypeKind = "OBJECT"
const Enum__TypeKindINTERFACE Enum__TypeKind = "INTERFACE"
const Enum__TypeKindUNION Enum__TypeKind = "UNION"
const Enum__TypeKindENUM Enum__TypeKind = "ENUM"
const Enum__TypeKindINPUT_OBJECT Enum__TypeKind = "INPUT_OBJECT"
const Enum__TypeKindLIST Enum__TypeKind = "LIST"
const Enum__TypeKindNON_NULL Enum__TypeKind = "NON_NULL"

type Enum__DirectiveLocation string

const Enum__DirectiveLocationQUERY Enum__DirectiveLocation = "QUERY"
const Enum__DirectiveLocationMUTATION Enum__DirectiveLocation = "MUTATION"
const Enum__DirectiveLocationSUBSCRIPTION Enum__DirectiveLocation = "SUBSCRIPTION"
const Enum__DirectiveLocationFIELD Enum__DirectiveLocation = "FIELD"
const Enum__DirectiveLocationFRAGMENT_DEFINITION Enum__DirectiveLocation = "FRAGMENT_DEFINITION"
const Enum__DirectiveLocationFRAGMENT_SPREAD Enum__DirectiveLocation = "FRAGMENT_SPREAD"
const Enum__DirectiveLocationINLINE_FRAGMENT Enum__DirectiveLocation = "INLINE_FRAGMENT"
const Enum__DirectiveLocationSCHEMA Enum__DirectiveLocation = "SCHEMA"
const Enum__DirectiveLocationSCALAR Enum__DirectiveLocation = "SCALAR"
const Enum__DirectiveLocationOBJECT Enum__DirectiveLocation = "OBJECT"
const Enum__DirectiveLocationFIELD_DEFINITION Enum__DirectiveLocation = "FIELD_DEFINITION"
const Enum__DirectiveLocationARGUMENT_DEFINITION Enum__DirectiveLocation = "ARGUMENT_DEFINITION"
const Enum__DirectiveLocationINTERFACE Enum__DirectiveLocation = "INTERFACE"
const Enum__DirectiveLocationUNION Enum__DirectiveLocation = "UNION"
const Enum__DirectiveLocationENUM Enum__DirectiveLocation = "ENUM"
const Enum__DirectiveLocationENUM_VALUE Enum__DirectiveLocation = "ENUM_VALUE"
const Enum__DirectiveLocationINPUT_OBJECT Enum__DirectiveLocation = "INPUT_OBJECT"
const Enum__DirectiveLocationINPUT_FIELD_DEFINITION Enum__DirectiveLocation = "INPUT_FIELD_DEFINITION"

type __Schema struct {
	Types            []__Type      `json:"types"`
	QueryType        __Type        `json:"queryType"`
	MutationType     *__Type       `json:"mutationType"`
	SubscriptionType *__Type       `json:"subscriptionType"`
	Directives       []__Directive `json:"directives"`
}

type __Type struct {
	Kind          Enum__TypeKind `json:"kind"`
	Name          *string        `json:"name"`
	Description   *string        `json:"description"`
	Fields        []__Field      `json:"fields"`
	Interfaces    []__Type       `json:"interfaces"`
	PossibleTypes []__Type       `json:"possibleTypes"`
	EnumValues    []__EnumValue  `json:"enumValues"`
	InputFields   []__InputValue `json:"inputFields"`
	OfType        *__Type        `json:"ofType"`
}

type __Field struct {
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	Args              []__InputValue `json:"args"`
	Type              __Type         `json:"type"`
	IsDeprecated      bool           `json:"isDeprecated"`
	DeprecationReason *string        `json:"deprecationReason"`
}

type __InputValue struct {
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	Type         __Type  `json:"type"`
	DefaultValue *string `json:"defaultValue"`
}

type __EnumValue struct {
	Name              string  `json:"name"`
	Description       *string `json:"description"`
	IsDeprecated      bool    `json:"isDeprecated"`
	DeprecationReason *string `json:"deprecationReason"`
}

type __Directive struct {
	Name        string                    `json:"name"`
	Description *string                   `json:"description"`
	Locations   []Enum__DirectiveLocation `json:"locations"`
	Args        []__InputValue            `json:"args"`
}

type ProductDiscountCustomizationFunctionRequest struct {
	Cart          *CartInput         `json:"cart"`
	DiscountNodes []*DiscountNode    `json:"discountNodes"`
	Localization  *LocalizationInput `json:"localization"`
}

//easyjson:json
type ProductDiscountCustomizationFunctionResponse struct {
	Discounts []*ProductDiscount `json:"discounts"`
}

type ProductDiscount struct {
	Code        *string                  `json:"code"`
	PriceRuleId *string                  `json:"priceRuleId"`
	Message     *string                  `json:"message"`
	Targets     []*ProductDiscountTarget `json:"targets"`
	Value       *ProductDiscountValue    `json:"value"`
}

type ProductDiscountTarget struct {
	CartLine *CartLineTarget `json:"cartLine"`
}

type CartLineTarget struct {
	Id       *string `json:"id"`
	Quantity *int64  `json:"quantity"`
}

type ProductDiscountValue struct {
	FixedAmount *ProductDiscountFixedAmount `json:"fixedAmount"`
	Percentage  *Percentage                 `json:"percentage"`
}

type ProductDiscountFixedAmount struct {
	Amount            *string `json:"amount"`
	AppliesToEachItem *bool   `json:"appliesToEachItem"`
}

type Percentage struct {
	Value *string `json:"value"`
}

type BuyerIdentityInput struct {
	Customer          *CustomerInput          `json:"customer"`
	Email             *string                 `json:"email"`
	Phone             *string                 `json:"phone"`
	PurchasingCompany *PurchasingCompanyInput `json:"purchasingCompany"`
}

type CartCostInput struct {
	SubtotalAmount *MoneyV2 `json:"subtotalAmount"`
}

type CartInput struct {
	BuyerIdentity *BuyerIdentityInput `json:"buyerIdentity"`
	Cost          *CartCostInput      `json:"cost"`
	Lines         []*CartLineInput    `json:"lines"`
}

type CartLineInput struct {
	Cost        *CartCostInput    `json:"cost"`
	Id          *string           `json:"id"`
	Merchandise *MerchandiseInput `json:"merchandise"`
	Quantity    *int64            `json:"quantity"`
}

type CompanyContactInput struct {
	Id *string `json:"id"`
}

type CompanyInput struct {
	Id   *string `json:"id"`
	Name *string `json:"name"`
}

type CompanyLocationInput struct {
	Id   *string `json:"id"`
	Name *string `json:"name"`
}

type CustomerInput struct {
	Email      *string      `json:"email"`
	Id         *string      `json:"id"`
	Metafields []*Metafield `json:"metafields"`
	Phone      *string      `json:"phone"`
}

type DiscountNode struct {
	Metafields  []*Metafield `json:"metafields"`
	PriceRuleId *string      `json:"priceRuleId"`
}

type Input struct {
	Cart          *CartInput         `json:"cart"`
	DiscountNodes []*DiscountNode    `json:"discountNodes"`
	Localization  *LocalizationInput `json:"localization"`
	__schema      __Schema           `json:"__schema"`
	__type        *__Type            `json:"__type"`
}

type LocalizationInput struct {
	Country  *string `json:"country"`
	Language *string `json:"language"`
	MarketId *string `json:"marketId"`
}

type MerchandiseInput struct {
	ProductVariant *ProductVariantInput `json:"productVariant"`
}

type Metafield struct {
	Key       string  `json:"key"`
	Namespace *string `json:"namespace"`
	Type      string  `json:"type"`
	Value     string  `json:"value"`
}

type MetafieldInput struct {
	Key       *string `json:"key"`
	Namespace *string `json:"namespace"`
}

type MoneyV2 struct {
	Amount       *string `json:"amount"`
	CurrencyCode *string `json:"currencyCode"`
}

type ProductInput struct {
	Handle           *string      `json:"handle"`
	Id               *string      `json:"id"`
	InSalesPlanGroup *bool        `json:"inSalesPlanGroup"`
	IsGiftCard       *string      `json:"isGiftCard"`
	Metafields       []*Metafield `json:"metafields"`
	ProductType      *int64       `json:"productType"`
	Title            *string      `json:"title"`
}

type ProductVariantInput struct {
	CompareAtPrice   *string       `json:"compareAtPrice"`
	IsCustom         *bool         `json:"isCustom"`
	Metafields       []*Metafield  `json:"metafields"`
	Price            *string       `json:"price"`
	Product          *ProductInput `json:"product"`
	RequiresShipping *bool         `json:"requiresShipping"`
	Sku              *string       `json:"sku"`
	Title            *string       `json:"title"`
	Weight           *string       `json:"weight"`
	WeightUnit       *string       `json:"weightUnit"`
}

type PurchasingCompanyInput struct {
	Company         *CompanyInput         `json:"company"`
	CompanyContact  *CompanyContactInput  `json:"companyContact"`
	CompanyLocation *CompanyLocationInput `json:"companyLocation"`
}
