// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package module

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule(in *jlexer.Lexer, out *__Type) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "kind":
			out.Kind = Enum__TypeKind(in.String())
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "fields":
			if in.IsNull() {
				in.Skip()
				out.Fields = nil
			} else {
				in.Delim('[')
				if out.Fields == nil {
					if !in.IsDelim(']') {
						out.Fields = make([]__Field, 0, 0)
					} else {
						out.Fields = []__Field{}
					}
				} else {
					out.Fields = (out.Fields)[:0]
				}
				for !in.IsDelim(']') {
					var v1 __Field
					(v1).UnmarshalEasyJSON(in)
					out.Fields = append(out.Fields, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "interfaces":
			if in.IsNull() {
				in.Skip()
				out.Interfaces = nil
			} else {
				in.Delim('[')
				if out.Interfaces == nil {
					if !in.IsDelim(']') {
						out.Interfaces = make([]__Type, 0, 0)
					} else {
						out.Interfaces = []__Type{}
					}
				} else {
					out.Interfaces = (out.Interfaces)[:0]
				}
				for !in.IsDelim(']') {
					var v2 __Type
					(v2).UnmarshalEasyJSON(in)
					out.Interfaces = append(out.Interfaces, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "possibleTypes":
			if in.IsNull() {
				in.Skip()
				out.PossibleTypes = nil
			} else {
				in.Delim('[')
				if out.PossibleTypes == nil {
					if !in.IsDelim(']') {
						out.PossibleTypes = make([]__Type, 0, 0)
					} else {
						out.PossibleTypes = []__Type{}
					}
				} else {
					out.PossibleTypes = (out.PossibleTypes)[:0]
				}
				for !in.IsDelim(']') {
					var v3 __Type
					(v3).UnmarshalEasyJSON(in)
					out.PossibleTypes = append(out.PossibleTypes, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "enumValues":
			if in.IsNull() {
				in.Skip()
				out.EnumValues = nil
			} else {
				in.Delim('[')
				if out.EnumValues == nil {
					if !in.IsDelim(']') {
						out.EnumValues = make([]__EnumValue, 0, 1)
					} else {
						out.EnumValues = []__EnumValue{}
					}
				} else {
					out.EnumValues = (out.EnumValues)[:0]
				}
				for !in.IsDelim(']') {
					var v4 __EnumValue
					(v4).UnmarshalEasyJSON(in)
					out.EnumValues = append(out.EnumValues, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "inputFields":
			if in.IsNull() {
				in.Skip()
				out.InputFields = nil
			} else {
				in.Delim('[')
				if out.InputFields == nil {
					if !in.IsDelim(']') {
						out.InputFields = make([]__InputValue, 0, 0)
					} else {
						out.InputFields = []__InputValue{}
					}
				} else {
					out.InputFields = (out.InputFields)[:0]
				}
				for !in.IsDelim(']') {
					var v5 __InputValue
					(v5).UnmarshalEasyJSON(in)
					out.InputFields = append(out.InputFields, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ofType":
			if in.IsNull() {
				in.Skip()
				out.OfType = nil
			} else {
				if out.OfType == nil {
					out.OfType = new(__Type)
				}
				(*out.OfType).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule(out *jwriter.Writer, in __Type) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"kind\":"
		out.RawString(prefix[1:])
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"fields\":"
		out.RawString(prefix)
		if in.Fields == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.Fields {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"interfaces\":"
		out.RawString(prefix)
		if in.Interfaces == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Interfaces {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"possibleTypes\":"
		out.RawString(prefix)
		if in.PossibleTypes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.PossibleTypes {
				if v10 > 0 {
					out.RawByte(',')
				}
				(v11).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"enumValues\":"
		out.RawString(prefix)
		if in.EnumValues == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.EnumValues {
				if v12 > 0 {
					out.RawByte(',')
				}
				(v13).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"inputFields\":"
		out.RawString(prefix)
		if in.InputFields == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.InputFields {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ofType\":"
		out.RawString(prefix)
		if in.OfType == nil {
			out.RawString("null")
		} else {
			(*in.OfType).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v __Type) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v __Type) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *__Type) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *__Type) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule1(in *jlexer.Lexer, out *__Schema) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "types":
			if in.IsNull() {
				in.Skip()
				out.Types = nil
			} else {
				in.Delim('[')
				if out.Types == nil {
					if !in.IsDelim(']') {
						out.Types = make([]__Type, 0, 0)
					} else {
						out.Types = []__Type{}
					}
				} else {
					out.Types = (out.Types)[:0]
				}
				for !in.IsDelim(']') {
					var v16 __Type
					(v16).UnmarshalEasyJSON(in)
					out.Types = append(out.Types, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "queryType":
			(out.QueryType).UnmarshalEasyJSON(in)
		case "mutationType":
			if in.IsNull() {
				in.Skip()
				out.MutationType = nil
			} else {
				if out.MutationType == nil {
					out.MutationType = new(__Type)
				}
				(*out.MutationType).UnmarshalEasyJSON(in)
			}
		case "subscriptionType":
			if in.IsNull() {
				in.Skip()
				out.SubscriptionType = nil
			} else {
				if out.SubscriptionType == nil {
					out.SubscriptionType = new(__Type)
				}
				(*out.SubscriptionType).UnmarshalEasyJSON(in)
			}
		case "directives":
			if in.IsNull() {
				in.Skip()
				out.Directives = nil
			} else {
				in.Delim('[')
				if out.Directives == nil {
					if !in.IsDelim(']') {
						out.Directives = make([]__Directive, 0, 0)
					} else {
						out.Directives = []__Directive{}
					}
				} else {
					out.Directives = (out.Directives)[:0]
				}
				for !in.IsDelim(']') {
					var v17 __Directive
					(v17).UnmarshalEasyJSON(in)
					out.Directives = append(out.Directives, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule1(out *jwriter.Writer, in __Schema) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"types\":"
		out.RawString(prefix[1:])
		if in.Types == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.Types {
				if v18 > 0 {
					out.RawByte(',')
				}
				(v19).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"queryType\":"
		out.RawString(prefix)
		(in.QueryType).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"mutationType\":"
		out.RawString(prefix)
		if in.MutationType == nil {
			out.RawString("null")
		} else {
			(*in.MutationType).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"subscriptionType\":"
		out.RawString(prefix)
		if in.SubscriptionType == nil {
			out.RawString("null")
		} else {
			(*in.SubscriptionType).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"directives\":"
		out.RawString(prefix)
		if in.Directives == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Directives {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v __Schema) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v __Schema) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *__Schema) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *__Schema) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule1(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule2(in *jlexer.Lexer, out *__InputValue) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "type":
			(out.Type).UnmarshalEasyJSON(in)
		case "defaultValue":
			if in.IsNull() {
				in.Skip()
				out.DefaultValue = nil
			} else {
				if out.DefaultValue == nil {
					out.DefaultValue = new(string)
				}
				*out.DefaultValue = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule2(out *jwriter.Writer, in __InputValue) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		(in.Type).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"defaultValue\":"
		out.RawString(prefix)
		if in.DefaultValue == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DefaultValue))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v __InputValue) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v __InputValue) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *__InputValue) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *__InputValue) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule2(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule3(in *jlexer.Lexer, out *__Field) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "args":
			if in.IsNull() {
				in.Skip()
				out.Args = nil
			} else {
				in.Delim('[')
				if out.Args == nil {
					if !in.IsDelim(']') {
						out.Args = make([]__InputValue, 0, 0)
					} else {
						out.Args = []__InputValue{}
					}
				} else {
					out.Args = (out.Args)[:0]
				}
				for !in.IsDelim(']') {
					var v22 __InputValue
					(v22).UnmarshalEasyJSON(in)
					out.Args = append(out.Args, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "type":
			(out.Type).UnmarshalEasyJSON(in)
		case "isDeprecated":
			out.IsDeprecated = bool(in.Bool())
		case "deprecationReason":
			if in.IsNull() {
				in.Skip()
				out.DeprecationReason = nil
			} else {
				if out.DeprecationReason == nil {
					out.DeprecationReason = new(string)
				}
				*out.DeprecationReason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule3(out *jwriter.Writer, in __Field) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Args {
				if v23 > 0 {
					out.RawByte(',')
				}
				(v24).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		(in.Type).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"isDeprecated\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDeprecated))
	}
	{
		const prefix string = ",\"deprecationReason\":"
		out.RawString(prefix)
		if in.DeprecationReason == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeprecationReason))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v __Field) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v __Field) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *__Field) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *__Field) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule3(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule4(in *jlexer.Lexer, out *__EnumValue) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "isDeprecated":
			out.IsDeprecated = bool(in.Bool())
		case "deprecationReason":
			if in.IsNull() {
				in.Skip()
				out.DeprecationReason = nil
			} else {
				if out.DeprecationReason == nil {
					out.DeprecationReason = new(string)
				}
				*out.DeprecationReason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule4(out *jwriter.Writer, in __EnumValue) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"isDeprecated\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDeprecated))
	}
	{
		const prefix string = ",\"deprecationReason\":"
		out.RawString(prefix)
		if in.DeprecationReason == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeprecationReason))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v __EnumValue) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v __EnumValue) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *__EnumValue) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *__EnumValue) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule4(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule5(in *jlexer.Lexer, out *__Directive) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "locations":
			if in.IsNull() {
				in.Skip()
				out.Locations = nil
			} else {
				in.Delim('[')
				if out.Locations == nil {
					if !in.IsDelim(']') {
						out.Locations = make([]Enum__DirectiveLocation, 0, 4)
					} else {
						out.Locations = []Enum__DirectiveLocation{}
					}
				} else {
					out.Locations = (out.Locations)[:0]
				}
				for !in.IsDelim(']') {
					var v25 Enum__DirectiveLocation
					v25 = Enum__DirectiveLocation(in.String())
					out.Locations = append(out.Locations, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "args":
			if in.IsNull() {
				in.Skip()
				out.Args = nil
			} else {
				in.Delim('[')
				if out.Args == nil {
					if !in.IsDelim(']') {
						out.Args = make([]__InputValue, 0, 0)
					} else {
						out.Args = []__InputValue{}
					}
				} else {
					out.Args = (out.Args)[:0]
				}
				for !in.IsDelim(']') {
					var v26 __InputValue
					(v26).UnmarshalEasyJSON(in)
					out.Args = append(out.Args, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule5(out *jwriter.Writer, in __Directive) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"locations\":"
		out.RawString(prefix)
		if in.Locations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v27, v28 := range in.Locations {
				if v27 > 0 {
					out.RawByte(',')
				}
				out.String(string(v28))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.Args {
				if v29 > 0 {
					out.RawByte(',')
				}
				(v30).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v __Directive) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v __Directive) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *__Directive) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *__Directive) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule5(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule6(in *jlexer.Lexer, out *RenameOperation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "paymentMethodId":
			if in.IsNull() {
				in.Skip()
				out.PaymentMethodId = nil
			} else {
				if out.PaymentMethodId == nil {
					out.PaymentMethodId = new(string)
				}
				*out.PaymentMethodId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule6(out *jwriter.Writer, in RenameOperation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"paymentMethodId\":"
		out.RawString(prefix)
		if in.PaymentMethodId == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PaymentMethodId))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RenameOperation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RenameOperation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RenameOperation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RenameOperation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule6(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule7(in *jlexer.Lexer, out *ProductVariant) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "product":
			(out.Product).UnmarshalEasyJSON(in)
		case "requiresShipping":
			out.RequiresShipping = bool(in.Bool())
		case "sku":
			if in.IsNull() {
				in.Skip()
				out.Sku = nil
			} else {
				if out.Sku == nil {
					out.Sku = new(string)
				}
				*out.Sku = string(in.String())
			}
		case "weight":
			if in.IsNull() {
				in.Skip()
				out.Weight = nil
			} else {
				if out.Weight == nil {
					out.Weight = new(float64)
				}
				*out.Weight = float64(in.Float64())
			}
		case "weightUnit":
			if in.IsNull() {
				in.Skip()
				out.WeightUnit = nil
			} else {
				if out.WeightUnit == nil {
					out.WeightUnit = new(string)
				}
				*out.WeightUnit = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule7(out *jwriter.Writer, in ProductVariant) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"product\":"
		out.RawString(prefix)
		(in.Product).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"requiresShipping\":"
		out.RawString(prefix)
		out.Bool(bool(in.RequiresShipping))
	}
	{
		const prefix string = ",\"sku\":"
		out.RawString(prefix)
		if in.Sku == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Sku))
		}
	}
	{
		const prefix string = ",\"weight\":"
		out.RawString(prefix)
		if in.Weight == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.Weight))
		}
	}
	{
		const prefix string = ",\"weightUnit\":"
		out.RawString(prefix)
		if in.WeightUnit == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.WeightUnit))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProductVariant) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProductVariant) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProductVariant) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProductVariant) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule7(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule8(in *jlexer.Lexer, out *Product) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "handle":
			out.Handle = string(in.String())
		case "id":
			out.Id = string(in.String())
		case "isGiftCard":
			out.IsGiftCard = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule8(out *jwriter.Writer, in Product) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"handle\":"
		out.RawString(prefix[1:])
		out.String(string(in.Handle))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"isGiftCard\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsGiftCard))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Product) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Product) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Product) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Product) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule8(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule9(in *jlexer.Lexer, out *PaymentCustomizationPaymentMethod) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule9(out *jwriter.Writer, in PaymentCustomizationPaymentMethod) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentCustomizationPaymentMethod) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentCustomizationPaymentMethod) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentCustomizationPaymentMethod) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentCustomizationPaymentMethod) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule9(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule10(in *jlexer.Lexer, out *PaymentCustomizationFunctionResponses) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(PaymentCustomizationFunctionResponses, 0, 2)
			} else {
				*out = PaymentCustomizationFunctionResponses{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v31 PaymentCustomizationFunctionResponse
			(v31).UnmarshalEasyJSON(in)
			*out = append(*out, v31)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule10(out *jwriter.Writer, in PaymentCustomizationFunctionResponses) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v32, v33 := range in {
			if v32 > 0 {
				out.RawByte(',')
			}
			(v33).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentCustomizationFunctionResponses) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentCustomizationFunctionResponses) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentCustomizationFunctionResponses) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentCustomizationFunctionResponses) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule10(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule11(in *jlexer.Lexer, out *PaymentCustomizationFunctionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "operations":
			if in.IsNull() {
				in.Skip()
				out.Operations = nil
			} else {
				in.Delim('[')
				if out.Operations == nil {
					if !in.IsDelim(']') {
						out.Operations = make([]Operation, 0, 2)
					} else {
						out.Operations = []Operation{}
					}
				} else {
					out.Operations = (out.Operations)[:0]
				}
				for !in.IsDelim(']') {
					var v34 Operation
					(v34).UnmarshalEasyJSON(in)
					out.Operations = append(out.Operations, v34)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule11(out *jwriter.Writer, in PaymentCustomizationFunctionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operations\":"
		out.RawString(prefix[1:])
		if in.Operations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v35, v36 := range in.Operations {
				if v35 > 0 {
					out.RawByte(',')
				}
				(v36).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentCustomizationFunctionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentCustomizationFunctionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentCustomizationFunctionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentCustomizationFunctionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule11(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule12(in *jlexer.Lexer, out *PaymentCustomizationFunctionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "checkout":
			if in.IsNull() {
				in.Skip()
				out.Checkout = nil
			} else {
				if out.Checkout == nil {
					out.Checkout = new(Checkout)
				}
				(*out.Checkout).UnmarshalEasyJSON(in)
			}
		case "localization":
			if in.IsNull() {
				in.Skip()
				out.Localization = nil
			} else {
				if out.Localization == nil {
					out.Localization = new(Localization)
				}
				(*out.Localization).UnmarshalEasyJSON(in)
			}
		case "paymentCustomizations":
			if in.IsNull() {
				in.Skip()
				out.PaymentCustomizations = nil
			} else {
				in.Delim('[')
				if out.PaymentCustomizations == nil {
					if !in.IsDelim(']') {
						out.PaymentCustomizations = make([]*PaymentCustomization, 0, 8)
					} else {
						out.PaymentCustomizations = []*PaymentCustomization{}
					}
				} else {
					out.PaymentCustomizations = (out.PaymentCustomizations)[:0]
				}
				for !in.IsDelim(']') {
					var v37 *PaymentCustomization
					if in.IsNull() {
						in.Skip()
						v37 = nil
					} else {
						if v37 == nil {
							v37 = new(PaymentCustomization)
						}
						(*v37).UnmarshalEasyJSON(in)
					}
					out.PaymentCustomizations = append(out.PaymentCustomizations, v37)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "presentmentCurrencyRate":
			if in.IsNull() {
				in.Skip()
				out.PresentmentCurrencyRate = nil
			} else {
				if out.PresentmentCurrencyRate == nil {
					out.PresentmentCurrencyRate = new(ExchangeRate)
				}
				(*out.PresentmentCurrencyRate).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule12(out *jwriter.Writer, in PaymentCustomizationFunctionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"checkout\":"
		out.RawString(prefix[1:])
		if in.Checkout == nil {
			out.RawString("null")
		} else {
			(*in.Checkout).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"localization\":"
		out.RawString(prefix)
		if in.Localization == nil {
			out.RawString("null")
		} else {
			(*in.Localization).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"paymentCustomizations\":"
		out.RawString(prefix)
		if in.PaymentCustomizations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v38, v39 := range in.PaymentCustomizations {
				if v38 > 0 {
					out.RawByte(',')
				}
				if v39 == nil {
					out.RawString("null")
				} else {
					(*v39).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"presentmentCurrencyRate\":"
		out.RawString(prefix)
		if in.PresentmentCurrencyRate == nil {
			out.RawString("null")
		} else {
			(*in.PresentmentCurrencyRate).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentCustomizationFunctionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentCustomizationFunctionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentCustomizationFunctionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentCustomizationFunctionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule12(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule13(in *jlexer.Lexer, out *PaymentCustomization) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "metafield":
			if in.IsNull() {
				in.Skip()
				out.Metafield = nil
			} else {
				if out.Metafield == nil {
					out.Metafield = new(Metafield)
				}
				(*out.Metafield).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule13(out *jwriter.Writer, in PaymentCustomization) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"metafield\":"
		out.RawString(prefix[1:])
		if in.Metafield == nil {
			out.RawString("null")
		} else {
			(*in.Metafield).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentCustomization) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentCustomization) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentCustomization) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentCustomization) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule13(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule14(in *jlexer.Lexer, out *Operation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "hide":
			if in.IsNull() {
				in.Skip()
				out.Hide = nil
			} else {
				if out.Hide == nil {
					out.Hide = new(HideOperation)
				}
				(*out.Hide).UnmarshalEasyJSON(in)
			}
		case "move":
			if in.IsNull() {
				in.Skip()
				out.Move = nil
			} else {
				if out.Move == nil {
					out.Move = new(MoveOperation)
				}
				(*out.Move).UnmarshalEasyJSON(in)
			}
		case "rename":
			if in.IsNull() {
				in.Skip()
				out.Rename = nil
			} else {
				if out.Rename == nil {
					out.Rename = new(RenameOperation)
				}
				(*out.Rename).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule14(out *jwriter.Writer, in Operation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hide\":"
		out.RawString(prefix[1:])
		if in.Hide == nil {
			out.RawString("null")
		} else {
			(*in.Hide).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"move\":"
		out.RawString(prefix)
		if in.Move == nil {
			out.RawString("null")
		} else {
			(*in.Move).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"rename\":"
		out.RawString(prefix)
		if in.Rename == nil {
			out.RawString("null")
		} else {
			(*in.Rename).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Operation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Operation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Operation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Operation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule14(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule15(in *jlexer.Lexer, out *MoveOperation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "index":
			if in.IsNull() {
				in.Skip()
				out.Index = nil
			} else {
				if out.Index == nil {
					out.Index = new(int64)
				}
				*out.Index = int64(in.Int64())
			}
		case "paymentMethodId":
			if in.IsNull() {
				in.Skip()
				out.PaymentMethodId = nil
			} else {
				if out.PaymentMethodId == nil {
					out.PaymentMethodId = new(string)
				}
				*out.PaymentMethodId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule15(out *jwriter.Writer, in MoveOperation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		if in.Index == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Index))
		}
	}
	{
		const prefix string = ",\"paymentMethodId\":"
		out.RawString(prefix)
		if in.PaymentMethodId == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PaymentMethodId))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MoveOperation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MoveOperation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MoveOperation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MoveOperation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule15(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule16(in *jlexer.Lexer, out *Money) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = string(in.String())
		case "currencyCode":
			out.CurrencyCode = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule16(out *jwriter.Writer, in Money) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"currencyCode\":"
		out.RawString(prefix)
		out.String(string(in.CurrencyCode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Money) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Money) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Money) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Money) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule16(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule17(in *jlexer.Lexer, out *Metafield) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule17(out *jwriter.Writer, in Metafield) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Metafield) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Metafield) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Metafield) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Metafield) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule17(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule18(in *jlexer.Lexer, out *MailingAddress) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address1":
			if in.IsNull() {
				in.Skip()
				out.Address1 = nil
			} else {
				if out.Address1 == nil {
					out.Address1 = new(string)
				}
				*out.Address1 = string(in.String())
			}
		case "address2":
			if in.IsNull() {
				in.Skip()
				out.Address2 = nil
			} else {
				if out.Address2 == nil {
					out.Address2 = new(string)
				}
				*out.Address2 = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
				out.City = nil
			} else {
				if out.City == nil {
					out.City = new(string)
				}
				*out.City = string(in.String())
			}
		case "company":
			if in.IsNull() {
				in.Skip()
				out.Company = nil
			} else {
				if out.Company == nil {
					out.Company = new(string)
				}
				*out.Company = string(in.String())
			}
		case "countryCode":
			if in.IsNull() {
				in.Skip()
				out.CountryCode = nil
			} else {
				if out.CountryCode == nil {
					out.CountryCode = new(string)
				}
				*out.CountryCode = string(in.String())
			}
		case "firstName":
			if in.IsNull() {
				in.Skip()
				out.FirstName = nil
			} else {
				if out.FirstName == nil {
					out.FirstName = new(string)
				}
				*out.FirstName = string(in.String())
			}
		case "lastName":
			if in.IsNull() {
				in.Skip()
				out.LastName = nil
			} else {
				if out.LastName == nil {
					out.LastName = new(string)
				}
				*out.LastName = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				*out.Phone = string(in.String())
			}
		case "provinceCode":
			if in.IsNull() {
				in.Skip()
				out.ProvinceCode = nil
			} else {
				if out.ProvinceCode == nil {
					out.ProvinceCode = new(string)
				}
				*out.ProvinceCode = string(in.String())
			}
		case "zip":
			if in.IsNull() {
				in.Skip()
				out.Zip = nil
			} else {
				if out.Zip == nil {
					out.Zip = new(string)
				}
				*out.Zip = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule18(out *jwriter.Writer, in MailingAddress) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address1\":"
		out.RawString(prefix[1:])
		if in.Address1 == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Address1))
		}
	}
	{
		const prefix string = ",\"address2\":"
		out.RawString(prefix)
		if in.Address2 == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Address2))
		}
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		if in.City == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.City))
		}
	}
	{
		const prefix string = ",\"company\":"
		out.RawString(prefix)
		if in.Company == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Company))
		}
	}
	{
		const prefix string = ",\"countryCode\":"
		out.RawString(prefix)
		if in.CountryCode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CountryCode))
		}
	}
	{
		const prefix string = ",\"firstName\":"
		out.RawString(prefix)
		if in.FirstName == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.FirstName))
		}
	}
	{
		const prefix string = ",\"lastName\":"
		out.RawString(prefix)
		if in.LastName == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.LastName))
		}
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		if in.Phone == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Phone))
		}
	}
	{
		const prefix string = ",\"provinceCode\":"
		out.RawString(prefix)
		if in.ProvinceCode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ProvinceCode))
		}
	}
	{
		const prefix string = ",\"zip\":"
		out.RawString(prefix)
		if in.Zip == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Zip))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MailingAddress) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MailingAddress) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MailingAddress) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MailingAddress) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule18(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule19(in *jlexer.Lexer, out *Localization) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "country":
			out.Country = string(in.String())
		case "language":
			out.Language = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule19(out *jwriter.Writer, in Localization) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix[1:])
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Localization) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule19(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Localization) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule19(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Localization) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule19(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Localization) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule19(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule20(in *jlexer.Lexer, out *Input) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "checkout":
			(out.Checkout).UnmarshalEasyJSON(in)
		case "localization":
			(out.Localization).UnmarshalEasyJSON(in)
		case "paymentCustomizations":
			if in.IsNull() {
				in.Skip()
				out.PaymentCustomizations = nil
			} else {
				in.Delim('[')
				if out.PaymentCustomizations == nil {
					if !in.IsDelim(']') {
						out.PaymentCustomizations = make([]*PaymentCustomization, 0, 8)
					} else {
						out.PaymentCustomizations = []*PaymentCustomization{}
					}
				} else {
					out.PaymentCustomizations = (out.PaymentCustomizations)[:0]
				}
				for !in.IsDelim(']') {
					var v40 *PaymentCustomization
					if in.IsNull() {
						in.Skip()
						v40 = nil
					} else {
						if v40 == nil {
							v40 = new(PaymentCustomization)
						}
						(*v40).UnmarshalEasyJSON(in)
					}
					out.PaymentCustomizations = append(out.PaymentCustomizations, v40)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "paymentMethods":
			if in.IsNull() {
				in.Skip()
				out.PaymentMethods = nil
			} else {
				in.Delim('[')
				if out.PaymentMethods == nil {
					if !in.IsDelim(']') {
						out.PaymentMethods = make([]*PaymentCustomizationPaymentMethod, 0, 8)
					} else {
						out.PaymentMethods = []*PaymentCustomizationPaymentMethod{}
					}
				} else {
					out.PaymentMethods = (out.PaymentMethods)[:0]
				}
				for !in.IsDelim(']') {
					var v41 *PaymentCustomizationPaymentMethod
					if in.IsNull() {
						in.Skip()
						v41 = nil
					} else {
						if v41 == nil {
							v41 = new(PaymentCustomizationPaymentMethod)
						}
						(*v41).UnmarshalEasyJSON(in)
					}
					out.PaymentMethods = append(out.PaymentMethods, v41)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "presentmentCurrencyRate":
			(out.PresentmentCurrencyRate).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule20(out *jwriter.Writer, in Input) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"checkout\":"
		out.RawString(prefix[1:])
		(in.Checkout).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"localization\":"
		out.RawString(prefix)
		(in.Localization).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"paymentCustomizations\":"
		out.RawString(prefix)
		if in.PaymentCustomizations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v42, v43 := range in.PaymentCustomizations {
				if v42 > 0 {
					out.RawByte(',')
				}
				if v43 == nil {
					out.RawString("null")
				} else {
					(*v43).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"paymentMethods\":"
		out.RawString(prefix)
		if in.PaymentMethods == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v44, v45 := range in.PaymentMethods {
				if v44 > 0 {
					out.RawByte(',')
				}
				if v45 == nil {
					out.RawString("null")
				} else {
					(*v45).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"presentmentCurrencyRate\":"
		out.RawString(prefix)
		(in.PresentmentCurrencyRate).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Input) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule20(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Input) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule20(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Input) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule20(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Input) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule20(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule21(in *jlexer.Lexer, out *HideOperation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "paymentMethodId":
			if in.IsNull() {
				in.Skip()
				out.PaymentMethodId = nil
			} else {
				if out.PaymentMethodId == nil {
					out.PaymentMethodId = new(string)
				}
				*out.PaymentMethodId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule21(out *jwriter.Writer, in HideOperation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"paymentMethodId\":"
		out.RawString(prefix[1:])
		if in.PaymentMethodId == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PaymentMethodId))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HideOperation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule21(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HideOperation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule21(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HideOperation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule21(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HideOperation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule21(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule22(in *jlexer.Lexer, out *ExchangeRate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "rate":
			out.Rate = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule22(out *jwriter.Writer, in ExchangeRate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rate\":"
		out.RawString(prefix[1:])
		out.String(string(in.Rate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExchangeRate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule22(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExchangeRate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule22(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExchangeRate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule22(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExchangeRate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule22(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule23(in *jlexer.Lexer, out *Customer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "displayName":
			out.DisplayName = string(in.String())
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				*out.Email = string(in.String())
			}
		case "id":
			out.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule23(out *jwriter.Writer, in Customer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"displayName\":"
		out.RawString(prefix[1:])
		out.String(string(in.DisplayName))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		if in.Email == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Email))
		}
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Customer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule23(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Customer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule23(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Customer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule23(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Customer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule23(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule24(in *jlexer.Lexer, out *CheckoutLineCost) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "subtotalAmount":
			(out.SubtotalAmount).UnmarshalEasyJSON(in)
		case "totalAmount":
			(out.TotalAmount).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule24(out *jwriter.Writer, in CheckoutLineCost) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subtotalAmount\":"
		out.RawString(prefix[1:])
		(in.SubtotalAmount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"totalAmount\":"
		out.RawString(prefix)
		(in.TotalAmount).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckoutLineCost) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule24(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckoutLineCost) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule24(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckoutLineCost) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule24(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckoutLineCost) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule24(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule25(in *jlexer.Lexer, out *CheckoutLine) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cost":
			(out.Cost).UnmarshalEasyJSON(in)
		case "id":
			out.Id = string(in.String())
		case "merchandise":
			(out.Merchandise).UnmarshalEasyJSON(in)
		case "quantity":
			out.Quantity = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule25(out *jwriter.Writer, in CheckoutLine) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cost\":"
		out.RawString(prefix[1:])
		(in.Cost).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"merchandise\":"
		out.RawString(prefix)
		(in.Merchandise).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"quantity\":"
		out.RawString(prefix)
		out.Int64(int64(in.Quantity))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckoutLine) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule25(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckoutLine) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule25(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckoutLine) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule25(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckoutLine) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule25(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule26(in *jlexer.Lexer, out *CheckoutDeliveryOption) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cost":
			(out.Cost).UnmarshalEasyJSON(in)
		case "deliveryMethodType":
			if in.IsNull() {
				in.Skip()
				out.DeliveryMethodType = nil
			} else {
				if out.DeliveryMethodType == nil {
					out.DeliveryMethodType = new(string)
				}
				*out.DeliveryMethodType = string(in.String())
			}
		case "description":
			out.Description = string(in.String())
		case "handle":
			out.Handle = string(in.String())
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				*out.Title = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule26(out *jwriter.Writer, in CheckoutDeliveryOption) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cost\":"
		out.RawString(prefix[1:])
		(in.Cost).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"deliveryMethodType\":"
		out.RawString(prefix)
		if in.DeliveryMethodType == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeliveryMethodType))
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"handle\":"
		out.RawString(prefix)
		out.String(string(in.Handle))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		if in.Title == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Title))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckoutDeliveryOption) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule26(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckoutDeliveryOption) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule26(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckoutDeliveryOption) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule26(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckoutDeliveryOption) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule26(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule27(in *jlexer.Lexer, out *CheckoutDeliveryGroup) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "checkoutLines":
			if in.IsNull() {
				in.Skip()
				out.CheckoutLines = nil
			} else {
				in.Delim('[')
				if out.CheckoutLines == nil {
					if !in.IsDelim(']') {
						out.CheckoutLines = make([]*CheckoutLine, 0, 8)
					} else {
						out.CheckoutLines = []*CheckoutLine{}
					}
				} else {
					out.CheckoutLines = (out.CheckoutLines)[:0]
				}
				for !in.IsDelim(']') {
					var v46 *CheckoutLine
					if in.IsNull() {
						in.Skip()
						v46 = nil
					} else {
						if v46 == nil {
							v46 = new(CheckoutLine)
						}
						(*v46).UnmarshalEasyJSON(in)
					}
					out.CheckoutLines = append(out.CheckoutLines, v46)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "deliveryAddress":
			if in.IsNull() {
				in.Skip()
				out.DeliveryAddress = nil
			} else {
				if out.DeliveryAddress == nil {
					out.DeliveryAddress = new(MailingAddress)
				}
				(*out.DeliveryAddress).UnmarshalEasyJSON(in)
			}
		case "deliveryOptions":
			if in.IsNull() {
				in.Skip()
				out.DeliveryOptions = nil
			} else {
				in.Delim('[')
				if out.DeliveryOptions == nil {
					if !in.IsDelim(']') {
						out.DeliveryOptions = make([]*CheckoutDeliveryOption, 0, 8)
					} else {
						out.DeliveryOptions = []*CheckoutDeliveryOption{}
					}
				} else {
					out.DeliveryOptions = (out.DeliveryOptions)[:0]
				}
				for !in.IsDelim(']') {
					var v47 *CheckoutDeliveryOption
					if in.IsNull() {
						in.Skip()
						v47 = nil
					} else {
						if v47 == nil {
							v47 = new(CheckoutDeliveryOption)
						}
						(*v47).UnmarshalEasyJSON(in)
					}
					out.DeliveryOptions = append(out.DeliveryOptions, v47)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "id":
			if in.IsNull() {
				in.Skip()
				out.Id = nil
			} else {
				in.Delim('[')
				if out.Id == nil {
					if !in.IsDelim(']') {
						out.Id = make([]*string, 0, 8)
					} else {
						out.Id = []*string{}
					}
				} else {
					out.Id = (out.Id)[:0]
				}
				for !in.IsDelim(']') {
					var v48 *string
					if in.IsNull() {
						in.Skip()
						v48 = nil
					} else {
						if v48 == nil {
							v48 = new(string)
						}
						*v48 = string(in.String())
					}
					out.Id = append(out.Id, v48)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "selectedDeliveryOption":
			if in.IsNull() {
				in.Skip()
				out.SelectedDeliveryOption = nil
			} else {
				if out.SelectedDeliveryOption == nil {
					out.SelectedDeliveryOption = new(CheckoutDeliveryOption)
				}
				(*out.SelectedDeliveryOption).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule27(out *jwriter.Writer, in CheckoutDeliveryGroup) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"checkoutLines\":"
		out.RawString(prefix[1:])
		if in.CheckoutLines == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v49, v50 := range in.CheckoutLines {
				if v49 > 0 {
					out.RawByte(',')
				}
				if v50 == nil {
					out.RawString("null")
				} else {
					(*v50).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"deliveryAddress\":"
		out.RawString(prefix)
		if in.DeliveryAddress == nil {
			out.RawString("null")
		} else {
			(*in.DeliveryAddress).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"deliveryOptions\":"
		out.RawString(prefix)
		if in.DeliveryOptions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v51, v52 := range in.DeliveryOptions {
				if v51 > 0 {
					out.RawByte(',')
				}
				if v52 == nil {
					out.RawString("null")
				} else {
					(*v52).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		if in.Id == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v53, v54 := range in.Id {
				if v53 > 0 {
					out.RawByte(',')
				}
				if v54 == nil {
					out.RawString("null")
				} else {
					out.String(string(*v54))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"selectedDeliveryOption\":"
		out.RawString(prefix)
		if in.SelectedDeliveryOption == nil {
			out.RawString("null")
		} else {
			(*in.SelectedDeliveryOption).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckoutDeliveryGroup) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule27(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckoutDeliveryGroup) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule27(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckoutDeliveryGroup) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule27(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckoutDeliveryGroup) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule27(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule28(in *jlexer.Lexer, out *CheckoutCost) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "subtotalAmount":
			(out.SubtotalAmount).UnmarshalEasyJSON(in)
		case "totalAmount":
			(out.TotalAmount).UnmarshalEasyJSON(in)
		case "totalTaxAmount":
			if in.IsNull() {
				in.Skip()
				out.TotalTaxAmount = nil
			} else {
				if out.TotalTaxAmount == nil {
					out.TotalTaxAmount = new(Money)
				}
				(*out.TotalTaxAmount).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule28(out *jwriter.Writer, in CheckoutCost) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subtotalAmount\":"
		out.RawString(prefix[1:])
		(in.SubtotalAmount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"totalAmount\":"
		out.RawString(prefix)
		(in.TotalAmount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"totalTaxAmount\":"
		out.RawString(prefix)
		if in.TotalTaxAmount == nil {
			out.RawString("null")
		} else {
			(*in.TotalTaxAmount).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckoutCost) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule28(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckoutCost) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule28(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckoutCost) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule28(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckoutCost) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule28(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule29(in *jlexer.Lexer, out *Checkout) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "buyerIdentity":
			if in.IsNull() {
				in.Skip()
				out.BuyerIdentity = nil
			} else {
				if out.BuyerIdentity == nil {
					out.BuyerIdentity = new(BuyerIdentity)
				}
				(*out.BuyerIdentity).UnmarshalEasyJSON(in)
			}
		case "cost":
			(out.Cost).UnmarshalEasyJSON(in)
		case "deliveryGroups":
			if in.IsNull() {
				in.Skip()
				out.DeliveryGroups = nil
			} else {
				in.Delim('[')
				if out.DeliveryGroups == nil {
					if !in.IsDelim(']') {
						out.DeliveryGroups = make([]*CheckoutDeliveryGroup, 0, 8)
					} else {
						out.DeliveryGroups = []*CheckoutDeliveryGroup{}
					}
				} else {
					out.DeliveryGroups = (out.DeliveryGroups)[:0]
				}
				for !in.IsDelim(']') {
					var v55 *CheckoutDeliveryGroup
					if in.IsNull() {
						in.Skip()
						v55 = nil
					} else {
						if v55 == nil {
							v55 = new(CheckoutDeliveryGroup)
						}
						(*v55).UnmarshalEasyJSON(in)
					}
					out.DeliveryGroups = append(out.DeliveryGroups, v55)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "lines":
			if in.IsNull() {
				in.Skip()
				out.Lines = nil
			} else {
				in.Delim('[')
				if out.Lines == nil {
					if !in.IsDelim(']') {
						out.Lines = make([]*CheckoutLine, 0, 8)
					} else {
						out.Lines = []*CheckoutLine{}
					}
				} else {
					out.Lines = (out.Lines)[:0]
				}
				for !in.IsDelim(']') {
					var v56 *CheckoutLine
					if in.IsNull() {
						in.Skip()
						v56 = nil
					} else {
						if v56 == nil {
							v56 = new(CheckoutLine)
						}
						(*v56).UnmarshalEasyJSON(in)
					}
					out.Lines = append(out.Lines, v56)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule29(out *jwriter.Writer, in Checkout) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"buyerIdentity\":"
		out.RawString(prefix[1:])
		if in.BuyerIdentity == nil {
			out.RawString("null")
		} else {
			(*in.BuyerIdentity).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"cost\":"
		out.RawString(prefix)
		(in.Cost).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"deliveryGroups\":"
		out.RawString(prefix)
		if in.DeliveryGroups == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v57, v58 := range in.DeliveryGroups {
				if v57 > 0 {
					out.RawByte(',')
				}
				if v58 == nil {
					out.RawString("null")
				} else {
					(*v58).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"lines\":"
		out.RawString(prefix)
		if in.Lines == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v59, v60 := range in.Lines {
				if v59 > 0 {
					out.RawByte(',')
				}
				if v60 == nil {
					out.RawString("null")
				} else {
					(*v60).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Checkout) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule29(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Checkout) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule29(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Checkout) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule29(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Checkout) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule29(l, v)
}
func easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule30(in *jlexer.Lexer, out *BuyerIdentity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "customer":
			if in.IsNull() {
				in.Skip()
				out.Customer = nil
			} else {
				if out.Customer == nil {
					out.Customer = new(Customer)
				}
				(*out.Customer).UnmarshalEasyJSON(in)
			}
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				*out.Email = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				*out.Phone = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule30(out *jwriter.Writer, in BuyerIdentity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"customer\":"
		out.RawString(prefix[1:])
		if in.Customer == nil {
			out.RawString("null")
		} else {
			(*in.Customer).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		if in.Email == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Email))
		}
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		if in.Phone == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Phone))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BuyerIdentity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule30(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BuyerIdentity) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule30(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BuyerIdentity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule30(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BuyerIdentity) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGopkgInshoplineComGsoulFunctionProxyTemplatePaymentCustomizationModule30(l, v)
}
