// Code generated by go generate; DO NOT EDIT.
// This file was generated from GraphQL schema

package module

type Enum__TypeKind string

const Enum__TypeKindSCALAR Enum__TypeKind = "SCALAR"
const Enum__TypeKindOBJECT Enum__TypeKind = "OBJECT"
const Enum__TypeKindINTERFACE Enum__TypeKind = "INTERFACE"
const Enum__TypeKindUNION Enum__TypeKind = "UNION"
const Enum__TypeKindENUM Enum__TypeKind = "ENUM"
const Enum__TypeKindINPUT_OBJECT Enum__TypeKind = "INPUT_OBJECT"
const Enum__TypeKindLIST Enum__TypeKind = "LIST"
const Enum__TypeKindNON_NULL Enum__TypeKind = "NON_NULL"

type Enum__DirectiveLocation string

const Enum__DirectiveLocationQUERY Enum__DirectiveLocation = "QUERY"
const Enum__DirectiveLocationMUTATION Enum__DirectiveLocation = "MUTATION"
const Enum__DirectiveLocationSUBSCRIPTION Enum__DirectiveLocation = "SUBSCRIPTION"
const Enum__DirectiveLocationFIELD Enum__DirectiveLocation = "FIELD"
const Enum__DirectiveLocationFRAGMENT_DEFINITION Enum__DirectiveLocation = "FRAGMENT_DEFINITION"
const Enum__DirectiveLocationFRAGMENT_SPREAD Enum__DirectiveLocation = "FRAGMENT_SPREAD"
const Enum__DirectiveLocationINLINE_FRAGMENT Enum__DirectiveLocation = "INLINE_FRAGMENT"
const Enum__DirectiveLocationSCHEMA Enum__DirectiveLocation = "SCHEMA"
const Enum__DirectiveLocationSCALAR Enum__DirectiveLocation = "SCALAR"
const Enum__DirectiveLocationOBJECT Enum__DirectiveLocation = "OBJECT"
const Enum__DirectiveLocationFIELD_DEFINITION Enum__DirectiveLocation = "FIELD_DEFINITION"
const Enum__DirectiveLocationARGUMENT_DEFINITION Enum__DirectiveLocation = "ARGUMENT_DEFINITION"
const Enum__DirectiveLocationINTERFACE Enum__DirectiveLocation = "INTERFACE"
const Enum__DirectiveLocationUNION Enum__DirectiveLocation = "UNION"
const Enum__DirectiveLocationENUM Enum__DirectiveLocation = "ENUM"
const Enum__DirectiveLocationENUM_VALUE Enum__DirectiveLocation = "ENUM_VALUE"
const Enum__DirectiveLocationINPUT_OBJECT Enum__DirectiveLocation = "INPUT_OBJECT"
const Enum__DirectiveLocationINPUT_FIELD_DEFINITION Enum__DirectiveLocation = "INPUT_FIELD_DEFINITION"

type __Schema struct {
	Types            []__Type      `json:"types"`
	QueryType        __Type        `json:"queryType"`
	MutationType     *__Type       `json:"mutationType"`
	SubscriptionType *__Type       `json:"subscriptionType"`
	Directives       []__Directive `json:"directives"`
}

type __Type struct {
	Kind          Enum__TypeKind `json:"kind"`
	Name          *string        `json:"name"`
	Description   *string        `json:"description"`
	Fields        []__Field      `json:"fields"`
	Interfaces    []__Type       `json:"interfaces"`
	PossibleTypes []__Type       `json:"possibleTypes"`
	EnumValues    []__EnumValue  `json:"enumValues"`
	InputFields   []__InputValue `json:"inputFields"`
	OfType        *__Type        `json:"ofType"`
}

type __Field struct {
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	Args              []__InputValue `json:"args"`
	Type              __Type         `json:"type"`
	IsDeprecated      bool           `json:"isDeprecated"`
	DeprecationReason *string        `json:"deprecationReason"`
}

type __InputValue struct {
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	Type         __Type  `json:"type"`
	DefaultValue *string `json:"defaultValue"`
}

type __EnumValue struct {
	Name              string  `json:"name"`
	Description       *string `json:"description"`
	IsDeprecated      bool    `json:"isDeprecated"`
	DeprecationReason *string `json:"deprecationReason"`
}

type __Directive struct {
	Name        string                    `json:"name"`
	Description *string                   `json:"description"`
	Locations   []Enum__DirectiveLocation `json:"locations"`
	Args        []__InputValue            `json:"args"`
}

type CartFlexFunctionRequest struct {
	Cart                    *Cart         `json:"cart"`
	CartFlex                *CartFlex     `json:"cartFlex"`
	Localization            *Localization `json:"localization"`
	PresentmentCurrencyRate *ExchangeRate `json:"presentmentCurrencyRate"`
	Shop                    *Shop         `json:"shop"`
}

//easyjson:json
type CartFlexFunctionResponse struct {
	Operations []*LineOperation `json:"operations"`
}

type LineOperation struct {
	LineExpand *LineExpandOperation `json:"lineExpand"`
	LinesMerge *LinesMergeOperation `json:"linesMerge"`
	LineUpdate *LineUpdateOperation `json:"lineUpdate"`
}

type LineExpandOperation struct {
	LineItemId        string              `json:"lineItemId"`
	ExpandedLineItems []*ExpandedLineItem `json:"expandedLineItems"`
	Image             *Image              `json:"image"`
	Price             *PriceAdjustment    `json:"price"`
	Title             *string             `json:"title"`
}

type ExpandedLineItem struct {
	Properties []*Property      `json:"properties"`
	VariantId  string           `json:"variantId"`
	Price      *PriceAdjustment `json:"price"`
	Quantity   int64            `json:"quantity"`
}

type LinesMergeOperation struct {
	LineItems       []*MergeLineItem `json:"lineItems"`
	Properties      []*Property      `json:"properties"`
	ParentVariantId string           `json:"parentVariantId"`
	Image           *Image           `json:"image"`
	Price           *PriceAdjustment `json:"price"`
	Title           *string          `json:"title"`
}

type MergeLineItem struct {
	LineItemId string `json:"lineItemId"`
	Quantity   int64  `json:"quantity"`
}

type LineUpdateOperation struct {
	LineItemId string           `json:"lineItemId"`
	Image      *Image           `json:"image"`
	Price      *PriceAdjustment `json:"price"`
	Title      *string          `json:"title"`
}

type Image struct {
	Url string `json:"url"`
}

type PriceAdjustment struct {
	PercentageAdjustment *PercentageAdjustment `json:"percentageAdjustment"`
	FixedPricePerUnit    *FixedPricePerUnit    `json:"fixedPricePerUnit"`
}
type PercentageAdjustment struct {
	Value *string `json:"value"`
}

type FixedPricePerUnit struct {
	Amount *string `json:"amount"`
}

type Attribute struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

type BuyerIdentity struct {
	Customer          *Customer          `json:"customer"`
	Email             *string            `json:"email"`
	Phone             *string            `json:"phone"`
	PurchasingCompany *PurchasingCompany `json:"purchasingCompany"`
}

type Cart struct {
	Attributes    []*Attribute   `json:"attributes"`
	BuyerIdentity *BuyerIdentity `json:"buyerIdentity"`
	Lines         []*LineItem    `json:"lines"`
	Metafields    []*Metafield   `json:"metafields"`
}

type CartFlex struct {
	Metafield *Metafield `json:"metafield"`
}

type Company struct {
	Id         string       `json:"id"`
	Metafields []*Metafield `json:"metafields"`
	Name       *string      `json:"name"`
}

type CompanyContact struct {
	Id string `json:"id"`
}

type CompanyLocation struct {
	Id   string  `json:"id"`
	Name *string `json:"name"`
}

type Customer struct {
	DisplayName string       `json:"displayName"`
	Email       *string      `json:"email"`
	Id          string       `json:"id"`
	Metafields  []*Metafield `json:"metafields"`
	Phone       *string      `json:"phone"`
}

type ExchangeRate struct {
	CurrencyCode *string `json:"currencyCode"`
	Rate         string  `json:"rate"`
}

type Input struct {
	Cart                    Cart         `json:"cart"`
	CartFlex                CartFlex     `json:"cartFlex"`
	Localization            Localization `json:"localization"`
	PresentmentCurrencyRate ExchangeRate `json:"presentmentCurrencyRate"`
	Shop                    *Shop        `json:"shop"`
	__schema                __Schema     `json:"__schema"`
	__type                  *__Type      `json:"__type"`
}

type LineItem struct {
	Cost        LineItemCost   `json:"cost"`
	Id          string         `json:"id"`
	Merchandise ProductVariant `json:"merchandise"`
	Properties  []*Property    `json:"properties"`
	Quantity    int64          `json:"quantity"`
}

type LineItemCost struct {
	FinalPrice     Money `json:"finalPrice"`
	Price          Money `json:"price"`
	SubtotalAmount Money `json:"subtotalAmount"`
	TotalAmount    Money `json:"totalAmount"`
}

type Localization struct {
	Country  string `json:"country"`
	Language string `json:"language"`
}

type Metafield struct {
	Key       string  `json:"key"`
	Namespace *string `json:"namespace"`
	Type      string  `json:"type"`
	Value     string  `json:"value"`
}

type MetafieldInput struct {
	Namespace *string `json:"namespace"`
	Key       *string `json:"key"`
}

type Money struct {
	Amount       string `json:"amount"`
	CurrencyCode string `json:"currencyCode"`
}

type Product struct {
	Category         *int64       `json:"category"`
	CustomCategory   *string      `json:"customCategory"`
	Handle           string       `json:"handle"`
	Id               string       `json:"id"`
	InSalesPlanGroup *bool        `json:"inSalesPlanGroup"`
	IsGiftCard       bool         `json:"isGiftCard"`
	Metafields       []*Metafield `json:"metafields"`
	Title            *string      `json:"title"`
}

type ProductVariant struct {
	CompareAtPrice   *Money       `json:"compareAtPrice"`
	Id               string       `json:"id"`
	IsCustom         *bool        `json:"isCustom"`
	Metafields       []*Metafield `json:"metafields"`
	Price            *Money       `json:"price"`
	Product          Product      `json:"product"`
	RequiresShipping bool         `json:"requiresShipping"`
	Sku              *string      `json:"sku"`
	Title            *string      `json:"title"`
	Weight           *float64     `json:"weight"`
	WeightUnit       *string      `json:"weightUnit"`
}

type Property struct {
	Additional     *string   `json:"additional"`
	ExtInfo        *string   `json:"extInfo"`
	Name           *string   `json:"name"`
	RoleVisibility *string   `json:"roleVisibility"`
	Show           *bool     `json:"show"`
	Type           *string   `json:"type"`
	Urls           []*string `json:"urls"`
	Value          *string   `json:"value"`
}

type PurchasingCompany struct {
	Company         *Company         `json:"company"`
	CompanyContact  *CompanyContact  `json:"companyContact"`
	CompanyLocation *CompanyLocation `json:"companyLocation"`
}

type Shop struct {
	LocalTime *string `json:"localTime"`
}
